title: 太极
bio:  太极生两仪，两仪生四象
baseurl: "/taiji"
url: "https://blog.codetiler.com"
repo: "taiji"                     #your_repo
client_id: "14ddfd53200b04059607" #your_clientID
secret: "693b6efa2874106e74d30317e72748c0837a2831"  #your_secrets
owner: "tonycheng1995"            #your_tonycheng1995
admin: ["tonycheng1995"]          #your_admin


email: tonycheng1995@foxmail.com
github: tonycheng1995
weibo:       #your_weiboID

markdown: kramdown

#分页
paginate: 10
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-feed           #文章提要
  - jekyll-sitemap        #站点地图
  - jekyll-gist
  - jekyll-email-protect  #邮件混淆
  - jekyll-seo-tag        #seo
  - jekyll-paginate      #分页